name: pipeline-notifier.yml
on:
  push:
    branches:
      - main

jobs:
  run_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Adding Githun detials to ENV
        run : |
          RUNID=${{ github.run_id }}
          REPO=${{ github.repository }}
          OWNER=${{ github.repository_owner }}

      - name: Running Shell Script
        run: |
          chmod +x ./src/notifier.sh
          ./src/notifier.sh $RUNID $REPO $OWNER
